dist: focal
language: python
services:
- docker
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
install:
#- sudo apt-get update
#- sudo apt-get install gcc-8
- pip install -r requirements.dev.txt
- pip install -e .
# https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/4
- pip install keyring==21.4.0
# see #337: flag potential twine issues before attempting to upload to PyPI
- python setup.py sdist
- python setup.py bdist_wheel
- twine check dist/*
script:
- tox
notifications:
  email: false
